---
name: WWW-Ohloh-API
version: 1.0_0
author:
  - 'Yanick Champoux <yanick@cpan.org>'
abstract: Ohloh API implementation
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=WWW-Ohloh-Api
  license: http://dev.perl.org/licenses/
  repository: http://babyl.dyndns.org/git/www-ohloh-api.git
requires:
  Date::Parse: 0
  Digest::MD5: 0
  HTML::HeadParser: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  Object::InsideOut: 0
  Params::Validate: 0
  Readonly: 0
  Test::More: 0
  Time::Piece: 0
  URI: 0
  XML::LibXML: 0
  XML::Writer: 0
  perl: 5.8.0
  version: 0
recommends:
  Test::Pod::Snippets: 0.04.01
provides:
  WWW::Ohloh::API:
    file: lib/WWW/Ohloh/API.pm
    version: 1.0_0
  WWW::Ohloh::API::Account:
    file: lib/WWW/Ohloh/API/Account.pm
    version: 1.0_0
  WWW::Ohloh::API::ActivityFact:
    file: lib/WWW/Ohloh/API/ActivityFact.pm
    version: 1.0_0
  WWW::Ohloh::API::ActivityFacts:
    file: lib/WWW/Ohloh/API/ActivityFacts.pm
    version: 1.0_0
  WWW::Ohloh::API::Analysis:
    file: lib/WWW/Ohloh/API/Analysis.pm
    version: 1.0_0
  WWW::Ohloh::API::Collection:
    file: lib/WWW/Ohloh/API/Collection.pm
    version: 1.0_0
  WWW::Ohloh::API::ContributorFact:
    file: lib/WWW/Ohloh/API/ContributorFact.pm
    version: 1.0_0
  WWW::Ohloh::API::ContributorLanguageFact:
    file: lib/WWW/Ohloh/API/ContributorLanguageFact.pm
    version: 1.0_0
  WWW::Ohloh::API::Enlistment:
    file: lib/WWW/Ohloh/API/Enlistment.pm
    version: 1.0_0
  WWW::Ohloh::API::Enlistments:
    file: lib/WWW/Ohloh/API/Enlistments.pm
    version: 1.0_0
  WWW::Ohloh::API::Factoid:
    file: lib/WWW/Ohloh/API/Factoid.pm
    version: 1.0_0
  WWW::Ohloh::API::Kudo:
    file: lib/WWW/Ohloh/API/Kudo.pm
    version: 1.0_0
  WWW::Ohloh::API::KudoScore:
    file: lib/WWW/Ohloh/API/KudoScore.pm
    version: 1.0_0
  WWW::Ohloh::API::Kudos:
    file: lib/WWW/Ohloh/API/Kudos.pm
    version: 1.0_0
  WWW::Ohloh::API::Language:
    file: lib/WWW/Ohloh/API/Language.pm
    version: 1.0_0
  WWW::Ohloh::API::Languages:
    file: lib/WWW/Ohloh/API/Languages.pm
    version: 1.0_0
  WWW::Ohloh::API::Message:
    file: lib/WWW/Ohloh/API/Message.pm
    version: 1.0_0
  WWW::Ohloh::API::Message::Tag:
    file: lib/WWW/Ohloh/API/Message/Tag.pm
    version: 1.0_0
  WWW::Ohloh::API::Messages:
    file: lib/WWW/Ohloh/API/Messages.pm
    version: 1.0_0
  WWW::Ohloh::API::Project:
    file: lib/WWW/Ohloh/API/Project.pm
    version: 1.0_0
  WWW::Ohloh::API::Projects:
    file: lib/WWW/Ohloh/API/Projects.pm
    version: 1.0_0
  WWW::Ohloh::API::Repository:
    file: lib/WWW/Ohloh/API/Repository.pm
    version: 1.0_0
  WWW::Ohloh::API::Role::Fetchable:
    file: lib/WWW/Ohloh/API/Role/Fetchable.pm
    version: 1.0_0
  WWW::Ohloh::API::Role::LoadXML:
    file: lib/WWW/Ohloh/API/Role/LoadXML.pm
  WWW::Ohloh::API::SizeFact:
    file: lib/WWW/Ohloh/API/SizeFact.pm
    version: 1.0_0
  WWW::Ohloh::API::Stack:
    file: lib/WWW/Ohloh/API/Stack.pm
    version: 1.0_0
  WWW::Ohloh::API::StackEntry:
    file: lib/WWW/Ohloh/API/StackEntry.pm
    version: 1.0_0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
