---
name: WWW-Ohloh-API
version: 0.0.6
author:
  - 'Yanick Champoux <yanick@cpan.org>'
abstract: Ohloh API implementation
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Digest::MD5: 0
  HTML::HeadParser: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  Object::InsideOut: 0
  Params::Validate: 0
  Readonly: 0
  Test::More: 0
  URI: 0
  XML::LibXML: 0
  XML::Writer: 0
  perl: 5.8.0
  version: 0
provides:
  WWW::Ohloh::API:
    file: lib/WWW/Ohloh/API.pm
    version: 0.0.6
  WWW::Ohloh::API::Account:
    file: lib/WWW/Ohloh/API/Account.pm
    version: 0.0.6
  WWW::Ohloh::API::ActivityFact:
    file: lib/WWW/Ohloh/API/ActivityFact.pm
    version: 0.0.6
  WWW::Ohloh::API::ActivityFacts:
    file: lib/WWW/Ohloh/API/ActivityFacts.pm
    version: 0.0.6
  WWW::Ohloh::API::Analysis:
    file: lib/WWW/Ohloh/API/Analysis.pm
    version: 0.0.6
  WWW::Ohloh::API::Kudo:
    file: lib/WWW/Ohloh/API/Kudo.pm
    version: 0.0.6
  WWW::Ohloh::API::KudoScore:
    file: lib/WWW/Ohloh/API/KudoScore.pm
    version: 0.0.6
  WWW::Ohloh::API::Kudos:
    file: lib/WWW/Ohloh/API/Kudos.pm
    version: 0.0.6
  WWW::Ohloh::API::Language:
    file: lib/WWW/Ohloh/API/Language.pm
    version: 0.0.6
  WWW::Ohloh::API::Languages:
    file: lib/WWW/Ohloh/API/Languages.pm
    version: 0.0.6
  WWW::Ohloh::API::Project:
    file: lib/WWW/Ohloh/API/Project.pm
    version: 0.0.6
  WWW::Ohloh::API::Projects:
    file: lib/WWW/Ohloh/API/Projects.pm
    version: 0.0.6
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
